"""The MAC processing element's design space: what is inside one PE, not how many there are.

The array's shape is given (D365): `lanes` products summed per cycle at the workload's own
precision. What is searched is the microarchitecture that computes them -- how each product is
formed, how the products are reduced, where the pipeline registers sit, and whether the PE
carries an accumulator input. Every point is generated by code (`rtl.py`), verified against
golden vectors by Verilator, and judged on ASAP7 by Yosys and OpenROAD; a model contributes by
INVENTING multiplier structures the enumeration does not contain (`invent.py`), never by
editing what the enumeration produces.

Small on purpose: 4 x 3 x 4 x 2 = 96 points. A space that can be screened exhaustively in
minutes does not need a proposer to pick from it; it needs a judge, and the model's effort goes
where the space ends.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, replace
from typing import Any, Iterable

#: How one signed product is formed. `behavioral` is the `*` operator, left to the synthesis
#: tool (Yosys lowers it to a shift-and-add array); the others are explicit structures.
MULTIPLIERS: tuple[str, ...] = ("behavioral", "array", "booth4", "wallace")
#: How `lanes` products become one sum: a ripple chain of adders, a balanced binary tree, or a
#: carry-save tree that defers every carry to one final adder.
REDUCERS: tuple[str, ...] = ("chain", "tree", "csa")
#: Register stages on the path. 0 is combinational; 1 registers the products; 2 also registers
#: the output; 3 also cuts the reduction in half. Latency in cycles equals the number.
PIPELINES: tuple[int, ...] = (0, 1, 2, 3)
#: What the technology mapper is told to optimise. "delay" hands ABC the clock period (every
#: number this repo pinned before, D278); "area" withholds it. Same RTL, different netlist:
#: a lever for area that costs frequency, and the study measures which (D366).
MAPPINGS: tuple[str, ...] = ("delay", "area")


class InvalidConfig(ValueError):
    """A configuration the generator cannot build."""


@dataclass(frozen=True)
class Shape:
    """What the workload fixes: lanes and precision. `acc_bits` is derived, never chosen."""

    lanes: int
    in_bits: int
    w_bits: int
    accumulate: bool = True

    @property
    def product_bits(self) -> int:
        return self.in_bits + self.w_bits

    @property
    def acc_bits(self) -> int:
        """Wide enough for the worst-case sum of `lanes` products, plus one bit of headroom
        for an accumulator input when the PE carries one (D202's rule, extended)."""
        bits = self.product_bits + (math.ceil(math.log2(self.lanes)) if self.lanes > 1 else 0)
        return bits + (1 if self.accumulate else 0)

    def describe(self) -> str:
        return (f"{self.lanes} lanes, int{self.in_bits} x int{self.w_bits} -> "
                f"int{self.acc_bits}" + (" with accumulator input" if self.accumulate else ""))


@dataclass(frozen=True)
class PeConfig:
    """One point of the space."""

    multiplier: str = "behavioral"
    reducer: str = "tree"
    pipeline: int = 0
    mapping: str = "delay"

    def knobs(self) -> dict[str, Any]:
        return {"multiplier": self.multiplier, "reducer": self.reducer, "pipeline": self.pipeline,
                "mapping": self.mapping}

    @property
    def rtl_label(self) -> str:
        """What the RTL is; the mapping is not part of it."""
        return f"{self.multiplier}-{self.reducer}-p{self.pipeline}"

    @property
    def label(self) -> str:
        return self.rtl_label + ("" if self.mapping == "delay" else f"-{self.mapping}")

    @property
    def clocked(self) -> bool:
        return self.pipeline > 0


#: The incumbent: what `flux_generation.derive_design_spec`'s canonical datapath is -- the `*`
#: operator and a sum, combinational, as every silicon number this repo has pinned was measured
#: (D225). Every gain is quoted against it.
DEFAULT = PeConfig(multiplier="behavioral", reducer="tree", pipeline=0)


def validate(cfg: PeConfig, multipliers: Iterable[str] = MULTIPLIERS) -> None:
    if cfg.multiplier not in tuple(multipliers):
        raise InvalidConfig(f"multiplier {cfg.multiplier!r} is not one of {list(multipliers)}")
    if cfg.reducer not in REDUCERS:
        raise InvalidConfig(f"reducer {cfg.reducer!r} is not one of {list(REDUCERS)}")
    if cfg.pipeline not in PIPELINES:
        raise InvalidConfig(f"pipeline {cfg.pipeline!r} is not one of {list(PIPELINES)}")
    if cfg.mapping not in MAPPINGS:
        raise InvalidConfig(f"mapping {cfg.mapping!r} is not one of {list(MAPPINGS)}")


def is_valid(cfg: PeConfig, multipliers: Iterable[str] = MULTIPLIERS) -> bool:
    try:
        validate(cfg, multipliers)
    except InvalidConfig:
        return False
    return True


def space(*, multipliers: Iterable[str] = MULTIPLIERS, reducers: Iterable[str] = REDUCERS,
          pipelines: Iterable[int] = PIPELINES, mappings: Iterable[str] = MAPPINGS
          ) -> list[PeConfig]:
    """Every point, incumbent first."""
    out = [PeConfig(m, r, p, mp) for m in multipliers for r in reducers for p in pipelines
           for mp in mappings]
    if DEFAULT in out:
        out.remove(DEFAULT)
        out.insert(0, DEFAULT)
    return out


def with_multiplier(cfg: PeConfig, multiplier: str) -> PeConfig:
    return replace(cfg, multiplier=multiplier)


__all__ = ["DEFAULT", "InvalidConfig", "MAPPINGS", "MULTIPLIERS", "PIPELINES", "PeConfig", "REDUCERS",
           "Shape", "is_valid", "space", "validate", "with_multiplier"]
