"""`flux_check_prose_faithfulness` — second-model cross-examination of an authored artifact
against the prose that requested it (docs/decisions.md D249): the semantic half of
prose-faithfulness, following D240's mechanical half (the backend-capability table).

Three design commitments:

1. **The judge reads a rendering, not the artifact.** The document summary the checker model
   sees is generated BY CODE from the parsed document — every semantic field, fixed wording —
   so the judge compares intent against content, never against JSON it might misread, and a
   field the renderer misses is a code bug caught by unit test rather than a silent blind spot.
2. **Tri-state verdict.** "faithful" | "unfaithful" | "unknown". A judge that cannot produce a
   parseable verdict after a bounded retry yields UNKNOWN — not a pass (that would make judge
   flakiness a rubber stamp) and not a fail (unknown is not evidence of a mismatch). Callers
   gate on `verdict == "faithful"` when they need the guarantee.
3. **The check is advisory power, bounded.** An "unfaithful" verdict carries the judge's named
   mismatches for the caller (or the authoring loop) to act on; it never mutates the artifact.
   Like D244's guidance, the judge can be wrong — the report keeps the full transcript so a
   human can overrule it with the evidence in hand.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from chia.base.ChiaFunction import ChiaFunction
from flux_llm import default_local_model, strip_markdown_fence

_DEFAULT_MODEL = default_local_model()

_JUDGE_PROMPT = """Two texts below. REQUEST is what a person asked for. DOCUMENT is what was
actually built (rendered mechanically, complete). Your only job: find requirements in REQUEST
that DOCUMENT gets wrong or leaves out.

REQUEST (what was asked):
{prose}

DOCUMENT (what was built):
{summary}

Work requirement by requirement:
- List each concrete thing REQUEST asks for (a metric, a number, a backend, an order).
- For each, copy the DOCUMENT line that answers it (or "missing" if none does).
- Mark matches=true when the line satisfies the ask — same value in different words IS a
  match — and matches=false only when the value differs or is missing.
- Things REQUEST never mentioned are not requirements.

Output ONLY a JSON object:
{{"checks": [{{"asked": "<what REQUEST asks>", "document_line": "<the DOCUMENT line, or 'missing'>", "matches": true/false}}]}}"""

_RETRY_PROMPT = """Your previous answer could not be parsed as the required JSON.

--- your previous answer ---
{prior}

Output ONLY the JSON object
{{"checks": [{{"asked": "...", "document_line": "...", "matches": true/false}}]}} — nothing else."""


def render_objective_summary(doc: dict[str, Any]) -> str:
    """Every semantic field of an Objective IR document, fixed wording, code-rendered —
    the complete content the judge sees (guarded complete by unit test)."""
    # Metric names glossed like the search kinds below, and for the same measured reason:
    # prose says "placed silicon area", the document says "area_mm2", and a judge that cannot
    # bridge the two reports a faithful document as missing its area objective.
    _METRIC_GLOSS = {
        "latency_cycles": "latency, in cycles",
        "energy_pj": "energy",
        "area_mm2": "silicon area (placed)",
        "power_w": "power",
    }
    lines = []
    for o in doc.get("objectives", []):
        where = o.get("measured_at", "screen")
        gloss = _METRIC_GLOSS.get(o["metric"])
        lines.append(f"- objective: {o['direction']} {o['metric']}"
                     + (f" i.e. {gloss}" if gloss else "")
                     + f" (measured at {where})")
    lines.append(f"- mode: {doc.get('mode')}")
    backends = doc.get("backends", {})
    lines.append(f"- screening backend: {backends.get('screening')}")
    lines.append(f"- escalation rungs, in order: {backends.get('escalation') or 'none'}")
    search = doc.get("search", {})
    # Enum values glossed in plain words: the judge compares against PROSE, and a raw enum the
    # prose never used ("composition_width" vs "per-layer engine widths") measured as a
    # hallucinated mismatch on a faithful document — terminology the renderer owns, not the judge.
    _KIND_GLOSS = {
        "architecture_width": "one global compute-array width",
        "composition_width": "per-op/per-layer engine widths for a multi-op workload",
        "memory_size": "memory level sizes",
        "joint": "array width and memory size together",
        "noc_topology": "NoC topology variants",
        "open_architecture": "the LLM invents whole new architectures",
    }
    kind = search.get("kind")
    gloss = _KIND_GLOSS.get(kind)
    parts = [f"kind={kind}" + (f" ({gloss})" if gloss else "")]
    for key in ("widths", "widths_per_op", "level", "sizes_kb", "variants"):
        if key in search:
            parts.append(f"{key}={search[key]}")
    lines.append(f"- search space: {', '.join(parts)}")
    strategy = doc.get("strategy", {})
    lines.append(f"- strategy: {strategy.get('kind')}"
                 + (f" (model {strategy['llm_model']})" if strategy.get("llm_model") else ""))
    lines.append(f"- budget: {doc.get('budget')}")
    if doc.get("stop"):
        lines.append(f"- stop criteria: {doc['stop']}")
    for c in doc.get("constraints") or ():
        lines.append(f"- constraint: {c}")
    return "\n".join(lines)


def render_design_spec_summary(spec: dict[str, Any]) -> str:
    """Every semantic field of a DesignSpec: module, ports with widths, the behavior text the
    generator will implement, and the vector count (values are computed, not intent)."""
    lines = [f"- module: {spec.get('module_name')}"]
    for p in spec.get("ports", []):
        lines.append(f"- port: {p.get('name')} ({p.get('dir')}, {p.get('dtype')}, "
                     f"{p.get('bits')} bits)")
    lines.append(f"- behavior: {spec.get('behavior')}")
    lines.append(f"- test vectors: {len(spec.get('test_vectors', []))} "
                 "(golden values computed from the executed reference, not authored intent)")
    return "\n".join(lines)


def _same_value(a: str, b: str) -> bool:
    """True when two mismatch sides state the same value — case/punctuation insensitive with
    light suffix stripping, so 'rtl and then openroad' == 'RTL, then OpenROAD' and
    'measure at screen' == 'measured at screen' (both measured live as hallucinated
    mismatches on faithful documents)."""
    import re

    def norm(s: str) -> str:
        tokens = re.sub(r"[^a-z0-9]+", " ", s.lower()).split()
        stemmed = []
        for tok in tokens:
            for suffix in ("ing", "ed", "s"):
                if tok.endswith(suffix) and len(tok) - len(suffix) >= 3:
                    tok = tok[: -len(suffix)]
                    break
            # final-e too, so 'measured'->'measur' meets 'measure'->'measur'
            if tok.endswith("e") and len(tok) >= 4:
                tok = tok[:-1]
            stemmed.append(tok)
        return " ".join(stemmed)

    return bool(norm(a)) and norm(a) == norm(b)


@dataclass
class FaithfulnessReport:
    verdict: str  # "faithful" | "unfaithful" | "unknown"
    mismatches: list[str]
    summary: str  # exactly what the judge saw as the document's content
    transcript: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "verdict": self.verdict,
            "mismatches": list(self.mismatches),
            "summary": self.summary,
            "transcript": list(self.transcript),
        }


@ChiaFunction()
def flux_check_prose_faithfulness(
    prose: str,
    objective: dict[str, Any] | None = None,
    design_spec: dict[str, Any] | None = None,
    *,
    model: str = _DEFAULT_MODEL,
    llm: Any | None = None,
    votes: int = 1,
) -> FaithfulnessReport:
    """Cross-examine an authored artifact (exactly one of `objective` / `design_spec`) against
    the prose that requested it. The judge model sees a code-rendered summary of the parsed
    document — never raw JSON — and returns faithful/unfaithful with named mismatches, or
    UNKNOWN when no parseable verdict emerges (never a silent pass). Advisory: the caller
    decides what an unfaithful or unknown verdict gates.

    `votes` > 1 runs that many INDEPENDENT judge passes and takes the majority verdict —
    measured necessity, not decoration (D249): a lone qwen-7b judge lands ~75-85% per
    direction even with the mechanical guards, and majority-of-3/5 buys the rest. Ties break
    to unfaithful (the cautious direction for an advisory check); mismatches are the union
    across unfaithful votes; all-unknown stays unknown."""
    if (objective is None) == (design_spec is None):
        raise ValueError("pass exactly one of objective= or design_spec=")
    summary = (render_objective_summary(objective) if objective is not None
               else render_design_spec_summary(design_spec))

    if llm is None:
        from chia.models.ollama import OllamaLLM

        llm = OllamaLLM(
            model=model,
            system_message="You are a precise reviewer. You output minimal, valid JSON only.",
        )

    if votes > 1:
        reports = [
            _single_check(prose, summary, llm) for _ in range(votes)
        ]
        counted = [r for r in reports if r.verdict != "unknown"]
        transcript = [line for r in reports for line in r.transcript]
        if not counted:
            return FaithfulnessReport(verdict="unknown", mismatches=[],
                                      summary=summary, transcript=transcript)
        unfaithful = [r for r in counted if r.verdict == "unfaithful"]
        if len(unfaithful) * 2 >= len(counted):  # majority, ties to unfaithful
            mismatches: list[str] = []
            for r in unfaithful:
                for m in r.mismatches:
                    if m not in mismatches:
                        mismatches.append(m)
            return FaithfulnessReport(verdict="unfaithful", mismatches=mismatches,
                                      summary=summary, transcript=transcript)
        return FaithfulnessReport(verdict="faithful", mismatches=[],
                                  summary=summary, transcript=transcript)

    return _single_check(prose, summary, llm)


def _single_check(prose: str, summary: str, llm: Any) -> FaithfulnessReport:
    transcript: list[str] = []
    prompt = _JUDGE_PROMPT.format(prose=prose, summary=summary)
    for attempt in (1, 2):  # one bounded retry on an unparseable verdict
        transcript.append(f"--- attempt {attempt} prompt ---\n{prompt}")
        raw = strip_markdown_fence(llm.prompt(prompt).result)
        transcript.append(f"--- attempt {attempt} response ---\n{raw}")
        try:
            doc = json.loads(raw)
            checks = doc["checks"]
            if not isinstance(checks, list) or not checks:
                raise ValueError("checks must be a non-empty list")
            # Only failed checks matter, and each passes two mechanical guards the structured
            # format buys (the D153-class fix for a small judge inventing distinctions,
            # measured live on faithful documents): a failed check whose two sides carry the
            # same value refutes itself, and one whose quoted document_line is not actually a
            # line of the rendered summary (and not "missing") judged text nobody showed it.
            mismatches = []
            summary_lines = {line.strip() for line in summary.splitlines()}
            for e in checks:
                if e.get("matches") is True:
                    continue
                asked = str(e.get("asked", "")).strip()
                document_line = str(e.get("document_line", "")).strip()
                if _same_value(asked, document_line):
                    transcript.append(
                        f"--- self-refuting check dropped ---\n{asked!r} == {document_line!r}")
                    continue
                if document_line.lower() != "missing" and document_line not in summary_lines \
                        and f"- {document_line}" not in summary_lines:
                    transcript.append(
                        f"--- fabricated document_line dropped ---\n{document_line!r}")
                    continue
                mismatches.append(f"requested: {asked}; document has: {document_line}")
            return FaithfulnessReport(
                verdict="faithful" if not mismatches else "unfaithful",
                mismatches=mismatches,
                summary=summary, transcript=transcript,
            )
        except Exception as exc:  # noqa: BLE001 — parse failure becomes the retry input
            transcript.append(f"--- attempt {attempt} parse error ---\n{type(exc).__name__}: {exc}")
            prompt = _RETRY_PROMPT.format(prior=raw[:2000])

    return FaithfulnessReport(
        verdict="unknown", mismatches=[], summary=summary, transcript=transcript)
