"""`flux_macarray_dse_loop` -- the MAC-PE microarchitecture study as one agent-callable node.

Generated SystemVerilog for every point of the PE space (multiplier structure, reduction,
pipeline depth), Verilator-verified against golden vectors derived from the workload, screened
by Yosys + OpenSTA and confirmed by OpenROAD placement on ASAP7 (docs/decisions.md D365). A
local model may invent multiplier structures beyond the four built in; every one that passes
its vectors joins the menu.
"""

from __future__ import annotations

from typing import Any

from chia.base.ChiaFunction import ChiaFunction


def _scored_payload(p) -> dict[str, Any]:
    return {"label": p.label, "config": p.config.knobs(), "proposed_by": p.provenance,
            **p.score.to_dict()}


@ChiaFunction()
def flux_macarray_dse_loop(
    db_path: str = "demo-macarray.db",
    *,
    workload: str | None = None,
    lanes: int = 8,
    accumulate: bool = True,
    target_mhz: float | None = 1000.0,
    preserve_fmax: bool = False,
    clock_period_ps: float | None = None,
    multipliers: list[str] | None = None,
    reducers: list[str] | None = None,
    pipelines: list[int] | None = None,
    mappings: list[str] | None = None,
    invent_rounds: int = 0,
    include_invented: bool = True,
    decide_on_finalists: int = 4,
    screen_only: bool = False,
    workers: int = 0,
    problem: str | None = None,
    llm_model: str | None = None,
    num_predict: int = 2400,
    seed: int = 0,
    feedback: Any | None = None,
) -> dict[str, Any]:
    """Search a MAC processing element's microarchitecture on real ASAP7 numbers.

    The array is given (`lanes` at the workload's precision); what is searched is inside the
    PE: how each product is formed (behavioral, shift-and-add array, radix-4 Booth, Wallace,
    plus anything a model invented), how the products are reduced (chain, tree, carry-save),
    and how deep the pipeline is (0-3 stages). Every design is generated by code, verified by
    Verilator, screened by synthesis + static timing, and the finalists along the fmax-vs-area
    frontier are placed. The decision is the smallest PE that makes `target_mhz`; with
    `preserve_fmax` the target is the incumbent's own measured clock on each rung, so the
    question becomes "how much area can go while the clock stays" (D366). `mappings` adds the
    technology mapper's recipe (delay-targeted or area-targeted ABC) to the space.
    """
    from flux_macarray.config import MULTIPLIERS
    from flux_macarray.flow import MacRequest, run_study

    request = MacRequest(
        db=db_path, workload=workload, lanes=lanes, accumulate=accumulate,
        target_mhz=target_mhz, preserve_fmax=preserve_fmax, clock_period_ps=clock_period_ps,
        multipliers=tuple(multipliers) if multipliers else MULTIPLIERS,
        reducers=tuple(reducers) if reducers else None,
        pipelines=tuple(pipelines) if pipelines else None,
        mappings=tuple(mappings) if mappings else None,
        invent_rounds=invent_rounds, include_invented=include_invented,
        decide_on_finalists=decide_on_finalists, screen_only=screen_only, workers=workers,
        problem=problem, seed=seed)
    ask = None
    if invent_rounds > 0:
        from flux_llm import local_proposer

        ask = local_proposer(model=llm_model, num_predict=num_predict)
    result = run_study(request, ask=ask, feedback=feedback)
    return {
        "decision": _scored_payload(result.decision) if result.decision else None,
        "decided_by": result.decided_by,
        "met_requirement": result.met_requirement,
        "incumbent": _scored_payload(result.incumbent) if result.incumbent else None,
        "frontier": [_scored_payload(p) for p in result.frontier],
        "screened": [_scored_payload(p) for p in result.screened],
        "confirmed": [_scored_payload(p) for p in result.confirmed],
        "shape": result.shape.describe() if result.shape else None,
        "lanes": result.shape.lanes if result.shape else lanes,
        "refused": [{"config": label, "why": why} for label, why in result.refused],
        "lessons": result.lessons,
        "not_established": result.not_established,
        "provenance": result.provenance,
    }
