"""`flux_macarray_dse_loop` -- the MAC-PE microarchitecture study as one agent-callable node.

Generated SystemVerilog for every point of the PE space (multiplier structure, reduction,
pipeline depth), Verilator-verified against golden vectors derived from the workload, screened
by Yosys + OpenSTA and confirmed by OpenROAD placement on ASAP7 (docs/decisions.md D365). A
local model may invent multiplier structures beyond the four built in; every one that passes
its vectors joins the menu.
"""

from __future__ import annotations

from typing import Any

from chia.base.ChiaFunction import ChiaFunction


def _scored_payload(p) -> dict[str, Any]:
    return {"label": p.label, "config": p.config.knobs(), "proposed_by": p.provenance,
            **p.score.to_dict()}


@ChiaFunction()
def flux_macarray_dse_loop(
    db_path: str = "demo-macarray.db",
    *,
    workload: str | None = None,
    lanes: int = 8,
    accumulate: bool = True,
    target_mhz: float | None = 1000.0,
    preserve_fmax: bool = False,
    clock_period_ps: float | None = None,
    multipliers: list[str] | None = None,
    reducers: list[str] | None = None,
    pipelines: list[int] | None = None,
    invent_rounds: int = 0,
    include_invented: bool = True,
    decide_on_finalists: int = 4,
    screen_only: bool = False,
    workers: int = 0,
    problem: str | None = None,
    llm_model: str | None = None,
    num_predict: int = 2400,
    seed: int = 0,
    feedback: Any | None = None,
) -> dict[str, Any]:
    """Search a MAC processing element's microarchitecture on real ASAP7 numbers.

    The array is given (`lanes` at the workload's precision); what is searched is inside the
    PE: how each product is formed (behavioral, shift-and-add array, radix-4 Booth, Wallace,
    plus anything a model invented), how the products are reduced (chain, tree, carry-save),
    and how deep the pipeline is (0-3 stages). Every design is generated by code, verified by
    Verilator, screened by synthesis + static timing, and the finalists along the fmax-vs-area
    frontier are placed. The decision is the smallest PE that makes `target_mhz`; with
    `preserve_fmax` the target is the incumbent's own measured clock on each stage, so the
    question becomes "how much area can go while the clock stays" (D366). `mappings` adds the
    technology mapper's recipe (delay-targeted or area-targeted ABC) to the space.
    """
    from pathlib import Path

    import yaml
    from flux_loop import PromptProblem, TaskSpec, request_for, run_loop
    from flux_macarray.world import pe_scored

    # the study's document (D533) with this call's ask
    doc_path = Path(__file__).resolve().parents[4] / "applications" / "macarray" / "macarray.problem.yaml"
    doc = yaml.safe_load(doc_path.read_text())
    doc["params"] = {**doc["params"], "workload": workload, "lanes": int(lanes), "accumulate": bool(accumulate),
                     "target_mhz": target_mhz, "preserve_fmax": bool(preserve_fmax), "clock_period_ps": clock_period_ps,
                     **({"multipliers": list(multipliers)} if multipliers else {}),
                     "reducers": list(reducers) if reducers else None, "pipelines": list(pipelines) if pipelines else None, "include_invented": bool(include_invented),
                     "problem": problem, "seed": int(seed)}
    if target_mhz:
        doc["objectives"][0]["goal"] = float(target_mhz)
    prob = PromptProblem(TaskSpec.from_dict(doc, base=doc_path.parent))
    request = request_for(prob.task, db=db_path, steps=1 + max(0, int(invent_rounds)),
                          finalists=max(0, int(decide_on_finalists)),
                          screen_only=bool(screen_only) or int(decide_on_finalists) <= 0, workers=int(workers))
    from ._loop_glue import loop_report, ollama_proposer, optional_proposer

    proposer = optional_proposer(invent_rounds, lambda: ollama_proposer(model=llm_model, num_predict=int(num_predict)))
    result = run_loop(prob, request, proposer=proposer, feedback=feedback, log=lambda _m: None)
    world = prob.world
    payload = lambda p: _scored_payload(pe_scored(p))                     # noqa: E731
    inc = world.incumbent(result)
    return loop_report(result, payload, refused_key="config", extra={
        "incumbent": _scored_payload(inc) if inc else None,
        "screened": [_scored_payload(p) for p in world.screened(result)],
        "confirmed": [_scored_payload(p) for p in world.confirmed(result)],
        "shape": world.shape.describe(),
        "lanes": world.shape.lanes,
        "report": world.report(result),
    })
