"""DEMO: 28 clients x 128b -> 32 banks, concurrent access, minimize area at >= 600 MHz.

Run it (a local model proposes; every candidate's RTL is generated by code, and every number
comes from a real tool):

    nix develop .#physical --command python3 applications/interconnect/demo.py
    nix develop .#physical --command python3 applications/interconnect/demo.py --llm-round 0  # no model

What it does, using this repo's own machinery end to end (docs/decisions.md D261):

  1. Builds an Objective IR document: minimize area, maximize concurrent throughput, with a
     hard constraint of fmax >= 600 MHz, over a space of interconnect topologies.
  2. SCREENS every topology with the instant structural evaluator (mux-bit proxy, peak
     concurrency, expected served-per-cycle under uniform traffic including bank conflicts).
  3. ESCALATES the survivors to the measured rung, where every reported number is measured
     and none is modelled: real Yosys synthesis and real OpenROAD placement on ASAP7 for
     every distinct arbitrated selector the topology uses (fitted across widths on ONE width
     set shared by all arities, then evaluated at 128 bits), and real Verilator simulation of
     the WHOLE fabric under uniform-random traffic for throughput (docs/decisions.md D266).
  4. Prints the trade-off frontier with the fidelity that produced each number, plus the
     memory the fabric serves (32 banks x 512 rows x 128b) characterized by real CACTI.

The screen's analytic throughput model is kept for ranking the space cheaply, and its error is
characterised rather than assumed: within ~10% of RTL wherever a fabric has one path per
destination, and up to 21% LOW where it has several and the router rotates among them.

Everything is durable: the campaign lives in a SQLite file, so an interrupted run resumes.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# applications/interconnect/demo.py -> the flux root. Two levels now, one before this file
# moved into its application: a depth-counted root is a hidden dependency on the tree's shape
# and this one silently pointed at applications/ after the move (docs/decisions.md D296).
FLUX_ROOT = Path(__file__).resolve().parents[2]

# Machinery that used to live in this file and is not about interconnects at all: any application
# running a long, tool-backed, model-directed search needs the same pieces (D298).
from flux_evaluator_abi.preflight import require_tools  # noqa: E402
from flux_knowledge_mining import fact_store_path, lessons_digest  # noqa: E402
from flux_llm import budget_chars, fit_to_budget, local_proposer  # noqa: E402
from flux_directed_search import Action, DirectedSearch, Outcome  # noqa: E402
from flux_search_campaign import (  # noqa: E402
    campaign_tally,
    measured_results,
    tally_lines,
    frontier_digest as _campaign_frontier_digest,
    next_proposal_series,
)

CLIENTS, BANKS, WIDTH_BITS = 28, 32, 128
BANK_ROWS = 512
TARGET_MHZ = 600.0


# Local Ollama; nothing leaves this machine. Overridable because the model on a given
# machine outlives any tag hard-coded here: `FLUX_LLM_MODEL=... python demos/...`.
LLM_MODEL = os.environ.get("FLUX_LLM_MODEL", "qwen3.8:latest")

# How many consecutive fruitless proposal rounds end a directed run. A BACKSTOP, not the
# stopping rule: the orchestrator is supposed to stop on its own, and this only catches a model
# that will not. Raising it lets a long run push further into the tail of the space at the cost of
# a few wasted rounds; it should never be 0, because a model that always answers "propose" would
# then run to the step cap every time.
BARREN_ROUNDS = int(os.environ.get("FLUX_BARREN_ROUNDS", "3"))

# How many contenders to MEASURE at once (docs/decisions.md D290). The tools at the measured rung
# are single-threaded processes, so one escalation pins one core: on a 64-core host a run sat at a
# load average of 12 while placing fabrics one at a time. Capped, because each concurrent
# placement is its own OpenROAD with its own memory.
ESCALATION_WORKERS = int(os.environ.get("FLUX_ESCALATION_WORKERS", "0")) or min(
    8, max(1, (os.cpu_count() or 4) // 4))


def objective_document(*, family: str = "staged", budget: int = 200, round_no: int = 1,
                       strategy: dict | None = None,
                       variants: list[dict] | None = None) -> dict:
    """The DSE for one round: every knob visible, nothing hidden in code."""
    return {
        "schema_version": "0.1.0",
        "id": (f"demo/interconnect-{CLIENTS}c-{BANKS}b-{WIDTH_BITS}bit/"
               f"round{round_no}-{family}/v1"),
        # Area against achievable concurrency. Latency is REPORTED per candidate but is not
        # an objective: as a screened metric it lets the 1-stage crossbar dominate the
        # contender set before timing is known, and its 1-cycle latency is a mirage if the
        # fabric cannot clock (measured: the direct crossbar closes at 483 MHz).
        "objectives": [
            {"metric": "area_mm2", "direction": "minimize", "measured_at": "escalation"},
            {"metric": "throughput_words_per_cycle", "direction": "maximize"},
            # The screen's own structural stand-in for area, and it is here because leaving it
            # out made the whole search degenerate: `area_mm2` exists only after escalation, so
            # a screen front built from throughput and wiring alone is won outright by the plain
            # crossbar, which maximises throughput at zero inter-stage wiring. It dominated every
            # round, exactly ONE contender escalated each time, and it then failed the 600 MHz
            # constraint - so the rounds measured nothing and the demo reported a frontier built
            # entirely from whatever the store already held. `mux_bits` restores the trade-off at
            # screen time, where it costs nothing. It earns the role by measurement rather than
            # plausibility: against the 23 fabrics in this repo's own store that have both a
            # screened `mux_bits` and a placed `area_mm2`, Pearson r = 0.95.
            {"metric": "mux_bits", "direction": "minimize"},
            # Wiring is a real cost the cell area omits, so it is an objective rather than a
            # footnote — otherwise a fabric of many tiny switches wins by hiding its wires.
            {"metric": "interstage_link_bits", "direction": "minimize"},
        ],
        "mode": "pareto",
        # The fabric serves this traffic; the workload document is required by the ABI and
        # hashed for provenance even though a fabric has no einsum to run.
        "workload": {"inline": {
            "schema_version": "0.1.0", "id": f"demo/{CLIENTS}-clients-{WIDTH_BITS}b",
            "ops": [{"id": "fabric_traffic", "kind": "compute_kernel",
                     "attrs": {"clients": CLIENTS, "banks": BANKS,
                               "width_bits": WIDTH_BITS}}],
        }},
        "base_arch": {"inline": {
            "schema_version": "0.1.0", "id": "demo/fabric",
            "tech": {"node": "n7", "pdk_class": "open"},
            "hierarchy": [
                {"level": "bank", "class": "memory",
                 "attrs": {"size_kb": BANK_ROWS * WIDTH_BITS / 8 / 1024,
                           "word_width_bits": WIDTH_BITS}},
            ],
        }},
        "backends": {"screening": "interconnect_struct", "escalation": ["interconnect_phys"]},
        # The PROBLEM, not a list of answers: Flux enumerates the topology space from
        # (clients, banks, width) itself — every interesting intermediate rank, every ordered
        # pair of ranks for 3-stage fabrics (which is what expresses asymmetric stages like
        # 4-then-7), and the radix-R networks the port count admits (docs/decisions.md D262).
        "search": {
            # The FULL depth and breadth, always: those two dials never partitioned anything,
            # every scope they described was a subset of the widest one (D308). What partitions
            # the space is the FAMILY, so that is what a round selects.
            "kind": "interconnect_topology", "clients": CLIENTS, "banks": BANKS,
            "width_bits": WIDTH_BITS, "max_stages": 4, "breadth": "wide",
            # A round built from NAMED variants enumerates nothing: perturbation defines its own
            # space against an incumbent, and enumerating a family beside it would drown the
            # neighbours it exists to measure.
            "families": [] if variants is not None else [family],
            # Discovery covers the monolithic-stage and radix-R families. A PARALLEL-SWITCH
            # fabric is a different structure — "first stage 4x4, second stage 7x8" means
            # seven 4x4 switches then four 7x8 switches, not one 28->28 crossbar — so it is
            # named explicitly and measured alongside everything the search found.
            "extra_variants": list(variants) if variants is not None else [
                {"kind": "xbar_staged", "clients": CLIENTS, "banks": BANKS,
                 "width_bits": WIDTH_BITS,
                 "stages": [{"switches": 7, "in": 4, "out": 4},
                            {"switches": 4, "in": 7, "out": 8}]},
                {"kind": "xbar_staged", "clients": CLIENTS, "banks": BANKS,
                 "width_bits": WIDTH_BITS,
                 "stages": [{"switches": 4, "in": 7, "out": 7},
                            {"switches": 7, "in": 4, "out": 5}]},
            ],
        },
        "strategy": strategy or {"kind": "grid", "seed": 0},
        # Screening a topology is instant in tool terms but still spends one evaluation from
        # the grant, so the grant covers the discovered space plus the physical rungs the
        # contenders earn (see ESCALATION_HEADROOM). The latch is real and has fired twice: at
        # 32 the campaign stopped mid-screen, and at a flat 400 the widest round spent
        # everything on screening and measured nothing at all.
        "budget": {"evaluations": budget},
        # The hard requirement: anything that cannot clock at 600 MHz is not a candidate,
        # whatever its area. Checked where fmax exists (the physical rung); screening trials
        # legally lack it and are not judged on it.
        "constraints": [
            {"kind": "metric_min", "metric": "fmax_mhz", "min": TARGET_MHZ,
             "measured_at": "escalation"},
            # Full concurrency is a REQUIREMENT, not a preference: the clients access the banks
            # at the same time, so a fabric whose narrowest point carries fewer than all of
            # them cannot serve the stated problem however cheap it is. Checked at SCREEN,
            # where the capacity is structural and free, so the search never spends a
            # place-and-route on a fabric that was disqualified by its own dimensions (D283).
            {"kind": "metric_min", "metric": "max_throughput_words_per_cycle",
             "min": CLIENTS, "measured_at": "screen"},
        ],
    }


def bank_area_mm2() -> tuple[float, str]:
    """The memory the fabric serves, characterized by real CACTI and scaled to 7nm with the
    published-bitcell floor (docs/decisions.md D255/D256) — reported alongside the fabric so
    the interconnect's share of total silicon is visible."""
    from flux_evaluator_cacti.adapter import CactiEvaluator, run_cacti
    from flux_evaluator_cacti.architecture_translator import architecture_ir_to_sram_spec
    from flux_evaluator_cacti.scaling import measure_area_efficiency, scale_area_mm2

    size_kb = BANK_ROWS * WIDTH_BITS / 8 / 1024
    arch = {"id": "bank", "tech": {"node": "n32"},
            "hierarchy": [{"level": "bank", "class": "memory",
                           "attrs": {"size_kb": size_kb, "word_width_bits": WIDTH_BITS}}]}
    binary = CactiEvaluator()._ensure_cacti_binary()
    native = run_cacti(architecture_ir_to_sram_spec(arch), technology_um=0.032,
                       cacti_path=str(binary))
    efficiency = measure_area_efficiency(arch, 0.032, cacti_path=str(binary))
    bits = int(size_kb * 1024 * 8)
    one_bank, note = scale_area_mm2(native.height_mm * native.width_mm, from_nm=32, to_nm=7,
                                    bits=bits, array_efficiency=efficiency)
    return one_bank * BANKS, note


# The scopes the rules can enumerate, in one place: the search's action variants, the `--rounds`
# default and the coverage report all read this. It used to exist twice, as a tuple of rounds and
# again as a set inside the validator, which is two things to keep in step for no gain.
# What a round may enumerate: one FAMILY of the space, at full depth and breadth. Families are
# disjoint and each reaches structures no other does, so choosing between them is a real decision
# and "which families were covered" is a real claim — neither of which was true of the nested
# depth/breadth scopes this replaced (docs/decisions.md D308).
from flux_interconnect.topology import FAMILIES as _FAMILIES  # noqa: E402

SCOPES = tuple({"family": f} for f in _FAMILIES)
SCOPE_KEYS = tuple(f for f in _FAMILIES)


# A screening trial costs one evaluation from the grant just as a place-and-route does, so a
# flat grant silently starves the widest round: at 400, round 4's 1137 candidates burned the
# whole budget on screening and escalated NOTHING, and the demo reported a frontier built
# entirely from the narrower rounds. The grant is therefore sized to the space the round
# actually offers, plus room for the rungs its contenders earn.
ESCALATION_HEADROOM = 150


def design_guidance(db: str) -> tuple[str, list]:
    """Everything the local model is allowed to know, from the two knowledge surfaces this repo
    already has (docs/decisions.md D270), kept as the different kinds of claim they are.

    CURATED: the referenceable IP catalog (what each family costs, when to use it, its published
    conditions and their scope) plus the retrieved `design-guidance` chunks on fabric selection.
    MEASURED: facts mined from this campaign's own store — what was actually built and what it
    came out at. A model handed only the second has no vocabulary; handed only the first it has
    no evidence about THIS silicon.
    """
    from flux_chia_nodes import flux_ip_catalog, flux_knowledge_lookup, flux_mine_knowledge

    catalog = flux_ip_catalog(interface="obi", status="constructible")
    lines = ["Interconnect IP available, with what is known about each:"]
    for ip in catalog["ip"]:
        lines.append(f"- {ip['title']}: {ip['summary']} Cost: {ip['cost_shape']}. "
                     f"Use when: {ip['when_to_use']}. Limits: {ip['known_limits']}")
        if ip["measured_here"]:
            lines.append(f"  Measured in this repo: {ip['measured_here']}")
    for query in ("interconnect fabric selection arity frequency",
                  "routing policy path diversity throughput"):
        for hit in flux_knowledge_lookup(query, standard_id="design-guidance", k=1)[:1]:
            lines.append("- " + str(hit["chunk"].get("text", ""))[:600])

    facts = flux_mine_knowledge(campaign_db_paths=[db]).get("facts", [])
    from flux_knowledge_mining import render_facts_for_prompt

    return fit_to_budget("\n".join(lines), facts, render_facts_for_prompt,
                         budget=KNOWLEDGE_BUDGET_CHARS)


# What the knowledge block may cost, in characters. Sized so guidance + facts + the strategy's own
# prompt + the model's answer fit a 4,096-token serving window at roughly 4 chars per token;
# `FLUX_PROMPT_BUDGET_CHARS` raises it for a machine serving a larger one.
KNOWLEDGE_BUDGET_CHARS = budget_chars()


def _mined_facts(db: str) -> list:
    """This study's own measurements as facts, for the lessons brief. Empty on any failure: a
    brief is advisory and must never be the reason a run does not start."""
    try:
        from flux_chia_nodes import flux_mine_knowledge

        return flux_mine_knowledge(campaign_db_paths=[db]).get("facts", [])
    except Exception:  # noqa: BLE001
        return []


def frontier_digest(db: str, limit: int = 6) -> str:
    """This application's frontier, in the shared renderer's terms: area first because area is
    the objective, then the constraint that decides whether a fabric counts at all."""
    return _campaign_frontier_digest(
        db, metrics=("area_mm2", "fmax_mhz", "throughput_words_per_cycle"), limit=limit)


def ceiling_for(variant: dict | None) -> int:
    """Transfers the fabric can carry at once: a count fixed by its narrowest point. Structural,
    so it is recomputed from the candidate rather than stored."""
    if not variant:
        return 0
    from flux_interconnect import build

    try:
        return build(variant).max_served_per_cycle()
    except Exception:  # noqa: BLE001 — a capacity we cannot derive is reported as unknown
        return 0


def measure_throughput_cached(topo) -> float:
    """Words per cycle from the RTL, memoised by fabric — the decision rung re-places a fabric
    but its throughput does not change with the switch implementation (D279 measured the two
    backends agreeing to within 0.02), so it is measured once."""
    from flux_interconnect.fabric import measure_throughput

    key = (topo.kind, tuple(sorted(topo.blocks.items())), topo.stages)
    if key not in _THROUGHPUT_CACHE:
        _THROUGHPUT_CACHE[key] = measure_throughput(topo, cycles=20000)[
            "measured_words_per_cycle"]
    return _THROUGHPUT_CACHE[key]


_THROUGHPUT_CACHE: dict = {}


def llm_round(db: str, round_no: object, budget: int) -> dict:
    """A round where the LOCAL MODEL proposes the fabrics (docs/decisions.md D269).

    The enumerated rounds can only widen within families someone wrote down; this one lets a
    the local model propose structures directly, having been handed the problem, this
    repo's own measured arity-to-frequency table, and everything measured so far. Nothing
    leaves the machine, and the model is on the PROPOSING side only: every fabric it names is
    built by the real constructor, routed constructively, screened, placed and simulated with
    the correctness checks of D268, exactly like an enumerated one. A bad proposal costs an
    evaluation and is recorded as a fallback; it cannot produce a wrong answer.
    """
    from flux_chia_nodes import (
        flux_campaign_frontier,
        flux_campaign_start,
        flux_campaign_status,
        flux_campaign_step,
    )

    # The grant covers the proposals PLUS the rungs they earn, and the strategy is capped at
    # the proposal count — otherwise screening eats the whole grant and the round, having
    # proposed a dozen fabrics, measures none of them.
    grant = budget + ESCALATION_HEADROOM
    doc = objective_document(
        family="hybrid", budget=grant, round_no=round_no,
        strategy={"kind": "generative_interconnect", "seed": 0, "llm_model": LLM_MODEL,
                  "max_proposals": budget},
    )
    doc["search"].pop("extra_variants", None)  # nothing named: the model does the naming
    started = flux_campaign_start(doc, db)
    print(f"\n=== round {round_no}: LOCAL LLM proposes {budget} fabrics ({LLM_MODEL})")
    guidance, facts = design_guidance(db)
    print(f"    handed the model {len(guidance):,} chars of curated guidance and "
          f"{len(facts)} measured facts from this run")
    report = flux_campaign_step(db, started["campaign_id"], max_trials=grant,
                                escalation_parallelism=ESCALATION_WORKERS,
                                calibration_db_path=_calibration_path(db),
                                knowledge_facts=facts,
                                knowledge_text=guidance)
    status = flux_campaign_status(db, started["campaign_id"])
    frontier = flux_campaign_frontier(db, started["campaign_id"], include_contenders=True)
    print(f"    {report['status']}: {status['trial_counts']}, "
          f"{len(frontier['contenders'])} contenders escalated")
    return {"campaign_id": started["campaign_id"], "report": report, "space": 0}


def run_round(db: str, round_no: int, family: str, budget: int | None) -> dict:
    """One campaign, driven entirely through the agent-surface tools."""
    from flux_chia_nodes import (
        flux_campaign_frontier,
        flux_campaign_start,
        flux_campaign_status,
        flux_campaign_step,
    )
    from flux_interconnect import enumerate_space

    space = enumerate_space(CLIENTS, BANKS, WIDTH_BITS, max_stages=4, breadth="wide",
                            max_candidates=5000, families=[family])
    doc = objective_document(family=family, round_no=round_no,
                             budget=budget or len(space) + ESCALATION_HEADROOM)
    extra = doc["search"].get("extra_variants") or []
    started = flux_campaign_start(doc, db)
    print(f"\n=== round {round_no}: the {family} family "
          f"-> {len(space) + len(extra)} candidates, budget {doc['budget']['evaluations']}")
    report = flux_campaign_step(db, started["campaign_id"], max_trials=10_000,
                                escalation_parallelism=ESCALATION_WORKERS,
                                calibration_db_path=_calibration_path(db))
    status = flux_campaign_status(db, started["campaign_id"])
    frontier = flux_campaign_frontier(db, started["campaign_id"], include_contenders=True)
    print(f"    {report['status']}: {status['trial_counts']}, "
          f"{len(frontier['contenders'])} contenders escalated, "
          f"budget left {status['remaining_budget'].get('evaluations')}")
    return {"campaign_id": started["campaign_id"], "report": report,
            "space": len(space) + len(extra)}


# The tools whose absence this demo must NOT survive quietly. Every number it prints is supposed
# to come from one of them, so a missing binary does not degrade the result, it removes it.
REQUIRED_TOOLS = {
    "openroad": "place-and-route (area, fmax)",
    "yosys": "synthesis",
    "verilator": "whole-fabric throughput simulation",
}


CONCLUSION_TIMEOUT_S = int(os.environ.get("FLUX_CONCLUSION_TIMEOUT_S", "300"))


def record_conclusions(db: str, ask, *, limit: int = 3) -> list[str]:
    """Ask the model what this run's measurements mean, and store what survives validation.

    Returns one display line per stored conclusion, empty when none were drawn. Never raises: a
    lesson is the most optional thing in the run, and losing it must not cost the results that
    were actually measured.
    """
    try:
        from flux_chia_nodes import flux_mine_knowledge
        from flux_knowledge_mining import FactStore, draft_conclusions, store_conclusions

        facts = flux_mine_knowledge(campaign_db_paths=[db]).get("facts", [])
        if not facts:
            return []
        # Refusals and frontier outcomes first: they are where a conclusion can actually come
        # from. A list of individual measured points invites restating one of them as a "lesson",
        # which the prompt forbids and the validator cannot detect.
        ranked = [f for f in facts if f.get("kind") in ("refusal_pattern", "frontier_outcome")]
        ranked += [f for f in facts if f.get("kind") == "estimator_bias"]
        # Its OWN short-lived model, not the orchestrator's. The shared default allows an hour
        # per call, which is right for a proposal the run depends on and wrong for a lesson it
        # does not: the results are already printed by this point, and nothing below needs this
        # to succeed. A lesson that costs an hour of a user's evening is not worth having.
        from flux_llm import local_proposer

        brief_ask = local_proposer(LLM_MODEL, timeout_s=CONCLUSION_TIMEOUT_S)
        drawn = draft_conclusions(ranked[:18], brief_ask, model=LLM_MODEL, limit=limit,
                                  scope=f"the interconnect study in {Path(db).name}")
        if not drawn:
            return []
        with FactStore(fact_store_path(db)) as store:
            store_conclusions(store, drawn, scope=f"interconnect study, {Path(db).name}")
        return [c.statement for c in drawn]
    except Exception as exc:  # noqa: BLE001
        print(f"    (no lessons recorded: {type(exc).__name__}: {str(exc)[:60]})")
        return []


def _calibration_path(db: str) -> str:
    """Residuals live beside the campaign store they were learned from, like its lessons do."""
    return str(Path(db).with_suffix(".calibration.db"))


def learn_from_placement(db: str, label: str, composed: dict, placed: dict) -> str:
    """Turn one whole-fabric placement into something the SCREEN can use (D305).

    A placement already produced the pair that matters: what composition predicted and what
    silicon did. Printed and discarded, it improves one row. Recorded as a residual, it corrects
    every screening estimate that follows, because the composed rung's error is systematic — it
    prices gates and none of the wire between them, so it runs optimistic on frequency by 100 to
    200 MHz (D280) and the 600 MHz constraint is applied to those optimistic numbers.

    Also written as a FACT, so the lessons brief can tell the orchestrator which fabrics have
    settled frequencies and by how much the screen missed. Deciding what to measure next is
    guesswork without it.
    """
    from flux_calibration import CalibrationStore
    from flux_evaluator_interconnect_phys.adapter import EVALUATOR_ID
    from flux_knowledge_mining import Fact, FactStore, fact_store_path

    note = ""
    predicted, reference = composed.get("fmax_mhz"), placed.get("fmax_mhz")
    if not predicted or not reference:
        return note
    error = (predicted - reference) / reference
    try:
        with CalibrationStore(_calibration_path(db)) as cal:
            cal.add_record(
                workload_hash=f"interconnect/{CLIENTS}c-{BANKS}b-{WIDTH_BITS}b",
                arch_hash=label, evaluator=EVALUATOR_ID, metric="fmax_mhz",
                predicted_value=float(predicted), reference_value=float(reference),
                reference_source="whole-fabric placement on the vendored core")
                # NO caveat, deliberately. `records_for` excludes caveated records from residual
                # statistics by default, so a caveat here would store every residual and use none
                # of them — the flywheel would spin without turning anything. The caveat field is
                # for comparisons that are not clean; composed-estimate against placed-silicon is
                # precisely the comparison being calibrated, and its nuance belongs in
                # `reference_source`, which names exactly what the reference was.
        note = (f"composed fmax read {error:+.0%} against placed silicon for {label} "
                f"({predicted:.0f} vs {reference:.0f} MHz)")
        with FactStore(fact_store_path(db)) as facts:
            facts.put_facts([Fact(
                kind="estimator_bias", statement=note,
                evidence={"label": label, "composed_fmax_mhz": predicted,
                          "placed_fmax_mhz": reference, "relative_error": error},
                scope=f"one fabric of this study, placed whole on the vendored core",
                not_established="that the same error applies to fabrics of other shapes or depths",
                pointers={"metric": "fmax_mhz", "evaluator": EVALUATOR_ID})])
    except Exception as exc:  # noqa: BLE001 — learning is optional, the measurement is not
        print(f"    (residual not recorded: {type(exc).__name__}: {str(exc)[:50]})")
    return note


def variants_round(db: str, round_no: object, variants: list[dict], label: str) -> dict:
    """A campaign whose whole space is a named list of fabrics — the neighbours of an incumbent.

    The same machinery as an enumerated round: each variant is built, routed, screened, and
    escalated if it earns it. What differs is only where the candidates came from.
    """
    from flux_chia_nodes import (
        flux_campaign_frontier,
        flux_campaign_start,
        flux_campaign_status,
        flux_campaign_step,
    )

    doc = objective_document(round_no=round_no, variants=variants,
                             budget=len(variants) + ESCALATION_HEADROOM)
    started = flux_campaign_start(doc, db)
    print(f"\n=== round {round_no}: {len(variants)} neighbours of {label}")
    report = flux_campaign_step(db, started["campaign_id"], max_trials=10_000,
                                escalation_parallelism=ESCALATION_WORKERS,
                                calibration_db_path=_calibration_path(db))
    status = flux_campaign_status(db, started["campaign_id"])
    frontier = flux_campaign_frontier(db, started["campaign_id"], include_contenders=True)
    print(f"    {report['status']}: {status['trial_counts']}, "
          f"{len(frontier['contenders'])} contenders escalated")
    return {"campaign_id": started["campaign_id"], "report": report, "space": len(variants)}


def step_cap(rounds: int, max_rounds: int, *, directed: bool) -> int:
    """How many steps a run may take.

    A directed run is bounded only by the runaway guard, because the orchestrator decides when it
    is finished (D291). An undirected one honours `--rounds`, which is the knob that makes the
    demo quick to try.

    A function rather than an expression inside `main()` because that expression was wrong and
    nothing could see it: moving the cap into the search loop turned `--rounds` into a silent
    no-op, a documented flag that did nothing, and it survived 1,428 tests because none of them
    can reach an argparse expression buried in a 300-line main.
    """
    return max_rounds if directed else max(1, rounds)


def main() -> int:
    import argparse

    # A step here can take minutes — an orchestrator call, a placement — and Python block-buffers
    # stdout whenever it is not a terminal. Piped to a file or a log, that turns a running demo
    # into a silent one and then a wall of text at the end. Line buffering shows the work.
    sys.stdout.reconfigure(line_buffering=True)
    from flux_profile import (elapsed_s as _elapsed, outside as _outside,
                              phase as _phase, report_lines, reset as _reset,
                              seconds as _seconds)
    _reset()  # the measurement window is this run, not this interpreter
    require_tools(REQUIRED_TOOLS,
                  hint="nix develop .#physical --command python3 "
                       "applications/interconnect/demo.py")

    from flux_store import CampaignStore

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--max-rounds", type=int, default=16, metavar="N",
                    help="runaway guard for a DIRECTED run: the orchestrator chooses how many "
                         "steps to take and when to stop, and this only bounds it (default 16)")
    ap.add_argument("--rounds", type=int, default=len(SCOPES),
                    help="how many widening rounds to run (1..4)")
    ap.add_argument("--budget", type=int, default=None,
                    help="evaluation grant per round (default: sized to the round's own space "
                         "— see ESCALATION_HEADROOM)")
    ap.add_argument("--db", default=str(FLUX_ROOT / "demo-interconnect.db"))
    ap.add_argument("--decide-on-finalists", type=int, default=0, metavar="N",
                    help="rank and DECIDE on the N best fabrics by placing each one whole on "
                         "the vendored xbar_varlat core — the screen mis-ranks (D272) and the "
                         "generated switch is 18-65%% slower than the vendored one (D279), so "
                         "neither should settle the choice")
    # ON by default (docs/decisions.md D286). A tool whose subject is AI for chip design should
    # not demonstrate itself with the AI switched off, and the proposer reaches structures the
    # enumeration cannot. `--llm-round 0` turns it off for a bit-reproducible run, which is
    # what the determinism was actually protecting.
    ap.add_argument("--llm-round", type=int, default=12, metavar="N",
                    help=f"let the local {LLM_MODEL} propose N fabrics after the enumerated "
                         "rounds (default 12; 0 skips it, for a fully deterministic run)")
    args = ap.parse_args()

    print(f"problem: {CLIENTS} clients x {WIDTH_BITS}b -> {BANKS} banks "
          f"({BANK_ROWS} rows each), CONCURRENT access")
    print(f"goal:    minimize fabric area, keep >= {TARGET_MHZ:.0f} MHz, and carry all "
          f"{CLIENTS} clients at once (a fabric with a narrower waist is refused, not ranked)")
    print(f"store:   {args.db}")

    # TWO ROLES, both local models (docs/decisions.md D287). The ORCHESTRATOR decides what the
    # search does next; the GENERATOR designs the fabrics. That split is this project's own
    # architecture rather than an embellishment, and it is the difference between a model that
    # fills in a fixed plan and one that runs the study.
    #
    # The orchestrator directs; it cannot quietly shrink the study. Every scope it does not run
    # is reported below, so an exploration that covered less says so out loud.
    # A DIRECTED run stops when the orchestrator says so, not after a fixed number of steps
    # (docs/decisions.md D291): once every scope is enumerated, `propose` is the only step that
    # can still find anything, and it is worth repeating. `--max-rounds` is a runaway guard, not
    # a plan. An undirected run still follows the fixed schedule exactly.
    ask = None
    if args.llm_round:
        try:
            ask = local_proposer(LLM_MODEL)
        except Exception as exc:  # noqa: BLE001 - no local model is a downgrade, not a failure
            print(f"\nno local model reachable ({type(exc).__name__}: {str(exc)[:60]}); "
                  "taking the next unrun option each step instead")

    attempted_at_start = campaign_tally(args.db)["attempted"]
    series = next_proposal_series(args.db)
    results: list[dict] = []

    # THE MENU, as data. Two entries today; a third capability is a third Action, not an edit to
    # the loop, the prompt and a dispatch (docs/decisions.md D298). The loop that consumes this
    # lives in `flux_directed_search` and knows nothing about fabrics.
    def _enumerate(params: dict) -> Outcome:
        before = campaign_tally(args.db)["attempted"]
        with _phase("round: enumerating (total)"):
            results.append(run_round(args.db, len(results) + 1, params["family"], args.budget))
        return Outcome(gained=campaign_tally(args.db)["attempted"] - before)

    def _propose(params: dict) -> Outcome:
        before = campaign_tally(args.db)["attempted"]
        with _phase("round: proposing (total)"):
            results.append(llm_round(args.db, f"{len(results) + 1}s{series}", params["count"]))
        return Outcome(gained=campaign_tally(args.db)["attempted"] - before)

    def _valid_scope(params: dict) -> dict | None:
        family = str(params.get("family", ""))
        return {"family": family} if family in SCOPE_KEYS else None

    def _variant_named(label: str) -> dict | None:
        for row in CampaignStore(args.db).list_campaigns():
            for trial in CampaignStore(args.db).trials(row["campaign_id"]):
                if trial.candidate.get("label") == label and trial.candidate.get("variant"):
                    return trial.candidate["variant"]
        return None

    def _measure(params: dict) -> Outcome:
        from flux_evaluator_interconnect_phys.adapter import EVALUATOR_ID

        """Place ONE named fabric for real, because the orchestrator asked.

        The screen composes per-arity block measurements and prices no wire between switches, so
        it runs optimistic on frequency by 100-200 MHz (D280). Until now only the final decision
        rung could settle that, at the very end. This lets the search spend a real placement
        mid-flight on a design it is unsure about, which is what a person would do.
        """
        from flux_interconnect import build
        from flux_interconnect.fabric import measure_whole_fabric

        label = str(params["label"])
        variant = _variant_named(label)
        if variant is None:
            return Outcome(progressed=False, detail=f"no fabric named {label} in this store")
        try:
            with _phase("on-demand placement (whole fabric)"):
                whole = measure_whole_fabric(build(variant), switch="vendored", timeout_s=5400)
        except Exception as exc:  # noqa: BLE001 — a failed placement is data, not a crash
            return Outcome(progressed=False,
                           detail=f"{label}: placement failed ({str(exc)[:60]})")
        detail = (f"{label} PLACED WHOLE: {whole['area_mm2']:.4f} mm2 at "
                  f"{whole['fmax_mhz']:.0f} MHz (measured, not composed)")
        print(f"    {detail}", flush=True)
        # Every placement teaches the screen, not just this row (D305). The composed estimate
        # comes from the store rather than a local table, because this runs mid-search and the
        # results table is not assembled until the end.
        composed_rows, _, _ = measured_results(
            CampaignStore(args.db), EVALUATOR_ID, {"fmax_mhz": "fmax_mhz"})
        learned = learn_from_placement(args.db, label, composed_rows.get(label, {}), whole)
        if learned:
            print(f"    learned: {learned}", flush=True)
            detail += f"; {learned}"
        # No new fabric was tried, and the step was still worth taking.
        return Outcome(progressed=True, detail=detail)

    def _perturb(params: dict) -> Outcome:
        """Search AROUND a known-good fabric rather than across the whole space.

        Enumeration covers what the rules express and proposing reaches what they cannot; neither
        answers "is there something slightly better next door", which is what a person asks after
        a good result and what a Monte-Carlo search is built on (docs/decisions.md D309).
        """
        from flux_interconnect.perturb import mutate

        label, radius = str(params["from"]), str(params["radius"])
        variant = _variant_named(label)
        if variant is None:
            return Outcome(progressed=False, detail=f"no fabric named {label} to perturb")
        try:
            neighbours = mutate(variant, radius=radius, limit=12)
        except ValueError as exc:
            return Outcome(progressed=False, detail=str(exc))
        if not neighbours:
            return Outcome(progressed=False, detail=f"{label} has no buildable {radius} neighbours")
        before = campaign_tally(args.db)["attempted"]
        with _phase("round: perturbing (total)"):
            results.append(variants_round(args.db, f"p{len(results) + 1}", neighbours,
                                          f"{label} ({radius})"))
        return Outcome(gained=campaign_tally(args.db)["attempted"] - before)

    def _valid_perturb(params: dict) -> dict | None:
        from flux_interconnect.perturb import RADII

        source, radius = str(params.get("from", "")), str(params.get("radius", "small"))
        return {"from": source, "radius": radius} if source and radius in RADII else None

    actions = [
        Action("perturb",
               "take one fabric already measured and try its NEIGHBOURS: a small radius changes "
               "one decision by one step, a large one changes the shape. Use it to improve on a "
               "good result rather than search the whole space again",
               _perturb, example={"from": "xbar_staged-7x4x4-4x7x8", "radius": "small"},
               variant_key=lambda p: f"perturbed:{p['from']}:{p['radius']}",
               validate=_valid_perturb),
        Action("measure",
               "place ONE fabric already in the store whole, with real Yosys and OpenROAD, "
               "instead of trusting the composed screen; costs minutes and settles a frequency",
               _measure, example={"label": "xbar_staged-7x4x4-4x7x8"},
               # Keyed by the fabric, so the loop refuses a second placement of one already
               # settled: minutes of Yosys and OpenROAD to reproduce a number the run already has.
               variant_key=lambda p: f"placed:{p['label']}",
               validate=lambda p: {"label": str(p["label"])} if p.get("label") else None),
        Action("enumerate",
               "derive one FAMILY of fabrics from the client and bank counts by rule and screen "
               "them; exhaustive for that family, and the families are disjoint",
               _enumerate, example={"family": "clos"},
               variants=SCOPES, variant_key=lambda p: p["family"],
               validate=_valid_scope),
        Action("propose",
               "ask a design model for fabrics the rules cannot express, such as one family "
               "feeding another; the only way to reach those",
               _propose, example={"count": 6},
               validate=lambda p: {"count": max(1, min(12, int(p.get("count", 6))))}),
    ]

    search = DirectedSearch(
        actions, ask=ask, cap=step_cap(args.rounds, args.max_rounds, directed=ask is not None),
        barren_limit=BARREN_ROUNDS,
        problem=(f"{CLIENTS} clients of {WIDTH_BITS} bits must reach {BANKS} banks at the same "
                 f"time, at >= {TARGET_MHZ:.0f} MHz, in the least silicon"),
        frontier=lambda: frontier_digest(args.db),
        lessons=lambda: lessons_digest(args.db, _mined_facts(args.db)))
    report = search.run()
    step = len(report.steps)

    if report.unexplored:
        covered = len(SCOPE_KEYS) - len(report.unexplored)
        print(f"\nCOVERAGE: {covered} of {len(SCOPE_KEYS)} families enumerated. "
              f"NOT explored: {', '.join(sorted(report.unexplored))}")
        print("    a study that looked at less has to say so; everything below is the best of "
              "what WAS explored, not of what exists")
    else:
        print(f"\nCOVERAGE: all {len(SCOPE_KEYS)} families enumerated")

    # How much of the space this study actually touched, in fabrics rather than trials. Printed
    # next to COVERAGE deliberately: coverage says which scopes were looked at, this says how much
    # was tried inside them, and a study is only as strong as both.
    # WHERE THE TIME WENT (docs/decisions.md D295). Printed before the results, because the cost
    # of a study is part of reading it: a frontier that took four minutes of cached lookups and
    # one that took an hour of place-and-route are not the same claim.
    # Derived by SUBTRACTION and labelled as such wherever it prints: a difference of two
    # measurements is not itself a measurement.
    derived = {}
    if _seconds("round: proposing (total)"):
        derived["proposing, outside the model"] = _outside("round: proposing (total)", "llm: ")
    if _seconds("round: enumerating (total)"):
        derived["enumerating, outside the tools"] = _outside("round: enumerating (total)", "tool:")
    print("\nWHERE THE TIME WENT")
    for line in report_lines(derived=derived):
        print("  " + line)
    orch_total = _seconds("llm: orchestrating (model)")
    if orch_total:
        print(f"  orchestration was {orch_total / max(_elapsed(), 1e-9) * 100:.0f}% of the run; "
              "every other decision in it is code")

    # WRITE DOWN WHAT THIS RUN MEANT, so the next one starts informed rather than rediscovering
    # the shape of the space (docs/decisions.md D297). Conclusions are INFERENCE and stored as
    # such, beside the store they were drawn from; a run with no model, or a model that declines,
    # simply records none.
    if ask is not None:
        # Announced BEFORE the call, not after: this is one model call over the run's own facts,
        # it can take minutes on local hardware, and a run that prints nothing while it waits is
        # indistinguishable from a hung one. Reported by an operator as "stuck after WHERE THE
        # TIME WENT", which is exactly where this used to go quiet.
        print(f"\ndrawing lessons from this run's measurements ({LLM_MODEL}, one call, "
              f"up to {CONCLUSION_TIMEOUT_S}s)...", flush=True)
        drawn = record_conclusions(args.db, ask)
        if drawn:
            print(f"\nLESSONS RECORDED: {len(drawn)} conclusion(s) drawn from this run's "
                  "measurements, for the next run to read")
            for line in drawn:
                print(f"    {line}")

    tally = campaign_tally(args.db)
    added = tally["attempted"] - attempted_at_start
    # BOTH numbers, because a resumed store makes them different and the difference is exactly
    # what D288 was about: a warm store can show a large total next to a run that added nothing.
    print("\nFABRICS ATTEMPTED: " + tally_lines(
        tally, added=added, steps=step, noun="fabrics",
        proposed_noun="proposed by the local model rather than enumerated by rule")[0])
    for line in tally_lines(tally, added=added, steps=step, noun="fabrics")[1:]:
        print(line)

    # Final answer: every measured candidate across all rounds, from the shared store — but
    # ONLY those measured by the evaluator method this code implements. A store outlives the
    # code that filled it, and a resumed store once put a radix-32 butterfly at 1012 MHz and
    # 0.0250 mm2 on the same table as current numbers; both came from a superseded fit, and
    # nothing on the row said so. Stale rows are counted and named, never silently dropped
    # and never silently mixed in.
    from flux_evaluator_interconnect_phys.adapter import EVALUATOR_ID

    store = CampaignStore(args.db)
    measured, rejected, stale = measured_results(
        store, EVALUATOR_ID,
        {"area_mm2": "area_mm2", "fmax_mhz": "fmax_mhz",
         "served": "throughput_words_per_cycle", "cycles": "latency_cycles",
         "links": "interstage_link_bits"},
        constraint_metric="fmax_mhz")
    for row in measured.values():
        # Derived from the candidate rather than read from the result: the ceiling is analytic and
        # costs nothing, and a store written before the metric existed would otherwise refuse the
        # whole row (D282).
        row["max_served"] = ceiling_for((row.pop("_candidate") or {}).get("variant"))

    print(f"\n=== MEASURED by {EVALUATOR_ID}: {len(measured)} fabrics, {len(rejected)} "
          f"rejected on the {TARGET_MHZ:.0f} MHz floor")
    if stale:
        versions = sorted(set(stale.values()))
        print(f"    ({len(stale)} result(s) in this store came from a SUPERSEDED evaluator "
              f"method — {', '.join(versions)} — and are excluded rather than mixed in.")
        print(f"     affected: {', '.join(sorted(stale)[:6])}"
              f"{' ...' if len(stale) > 6 else ''}. Delete the store to re-measure them.)")
    print("    area and fmax: real Yosys + OpenROAD on ASAP7, per distinct selector arity, "
          "fitted over widths 8/16/32 and evaluated at 128b")
    print("    served/cycle:  real Verilator on the whole generated fabric, 20k cycles of "
          "uniform-random traffic (not the screen's model)")
    print("    max/cycle:     transfers the fabric can carry AT ONCE, a count fixed by its "
          "narrowest point. A structural capacity, so it does not move with the traffic")
    ideal = BANKS * (1 - (1 - 1 / BANKS) ** CLIENTS)
    print(f"    of max:        share of that capacity this traffic actually uses. Uniform-random "
          f"targets collide, so even a perfect crossbar averages {ideal:.1f} of its {CLIENTS}")
    print(f"  {'topology':<34} {'area mm2':>9} {'fmax MHz':>9} {'served/cyc':>11} "
          f"{'max/cyc':>8} {'of max':>7} {'link bits':>10} {'cycles':>7}")
    for label, m in sorted(measured.items(), key=lambda kv: -kv[1]["served"]):
        # the ceiling beside the rate: bank conflicts, or the structure's own waist (D282)
        capacity = int(m.get("max_served") or 0)
        share = f"{m['served'] / capacity:.0%}" if capacity else "--"
        print(f"  {label:<34} {m['area_mm2']:>9.4f} {m['fmax_mhz']:>9.0f} "
              f"{m['served']:>11.1f} {capacity:>8d} {share:>7} "
              f"{m['links']:>10,.0f} {m['cycles']:>7.0f}")
    for label, fmax in sorted(rejected.items(), key=lambda kv: -kv[1]):
        print(f"  {label:<34} {'--':>9} {fmax:>9.0f}  REJECTED (< {TARGET_MHZ:.0f} MHz)")

    qualifying = {k: v for k, v in measured.items() if v["fmax_mhz"] >= TARGET_MHZ}
    if qualifying:
        best = max(qualifying.items(), key=lambda kv: (kv[1]["served"], -kv[1]["area_mm2"]))
        cheapest = min(qualifying.items(), key=lambda kv: kv[1]["area_mm2"])
        print(f"\nHIGHEST THROUGHPUT that meets timing: {best[0]} — "
              f"{best[1]['served']:.1f} words/cycle, {best[1]['area_mm2']:.4f} mm2, "
              f"{best[1]['fmax_mhz']:.0f} MHz, {best[1]['cycles']:.0f} cycle(s)")
        print(f"SMALLEST that meets timing:            {cheapest[0]} — "
              f"{cheapest[1]['area_mm2']:.4f} mm2 at {cheapest[1]['served']:.1f} words/cycle")

    decision = None
    if args.decide_on_finalists and qualifying:
        # THE DECISION RUNG (docs/decisions.md D280). Everything above it is a screen: the
        # composed rung prices each selector arity in isolation and multiplies by count, so it
        # sees no wire between switches at all, and it does not preserve the ORDER
        # (D272). This places each finalist WHOLE — and on the vendored PULP `xbar_varlat`
        # core rather than this repo's generated switch, which measured 18% to 65% slower and
        # ~30% larger on every family (D279). A ranking is only worth as much as the worst
        # implementation in it, so the decision is made on the better one.
        from flux_interconnect import build
        from flux_interconnect.fabric import measure_whole_fabric

        # Chosen by the OBJECTIVE, which is to minimise area — not by throughput. An earlier
        # cut ranked finalists by `served` descending, so a study whose stated goal is the least
        # silicon placed its five fastest fabrics and never placed its smallest one at all. The
        # decision rung then answered a question the demo was not asking, and reported NO
        # DECISION without the area winner ever having been tried on the vendored core.
        by_area = sorted(qualifying.items(), key=lambda kv: kv[1]["area_mm2"])
        finalists = by_area[: args.decide_on_finalists]
        # The frontier's other end is carried too, when there is room: the fastest fabric is not
        # the answer to this objective, but a decision rung that shows only one end of a trade-off
        # hides the shape of it.
        leader = max(qualifying.items(), key=lambda kv: kv[1]["served"])
        if leader[0] not in {k for k, _ in finalists} and len(finalists) > 1:
            finalists = finalists[:-1] + [leader]
        print(f"\n=== DECISION RUNG: {len(finalists)} finalists placed WHOLE on vendored "
              f"xbar_varlat (real Yosys + OpenROAD, every inter-switch wire included)")
        print("    ranked by AREA, the objective; the throughput leader is carried for contrast")
        # Printed as each finalist lands, not batched at the end: a whole-fabric placement is
        # minutes, so a silent half hour tells the operator nothing about whether it is working.
        print(f"  {'topology':<38} {'mm2':>8} {'MHz':>6} {'mW':>7} "
              f"{'served':>7} {'cyc':>4}  {'screen said':>12}")
        ranked = []
        for label, m in finalists:
            variant = next(
                (t.candidate["variant"] for row in store.list_campaigns()
                 for t in store.ok_trials(row["campaign_id"], phase="escalate")
                 if t.candidate.get("label") == label and t.candidate.get("variant")), None)
            if variant is None:
                continue
            topo = build(variant)
            try:
                with _phase("decision rung: one whole placement"):
                    whole = measure_whole_fabric(topo, switch="vendored", timeout_s=5400)
                served = measure_throughput_cached(topo)
                ranked.append((label, whole, served, m))
                learn_from_placement(args.db, label, m, whole)
                print(f"  {label:<38} {whole['area_mm2']:>8.4f} {whole['fmax_mhz']:>6.0f} "
                      f"{whole['power_total_w']*1e3:>7.1f} {served:>7.1f} "
                      f"{m['cycles']:>4.0f}  {m['area_mm2']:>7.4f}mm2", flush=True)
            except Exception as exc:  # noqa: BLE001 — a failed placement is data, not a crash
                print(f"  {label:<38} vendored placement failed: {str(exc)[:50]}")

        if ranked:
            # The decision itself, on measured silicon: meet the floor, then the most
            # throughput per mm2 of fabric.
            meeting = [r for r in ranked if r[1]["fmax_mhz"] >= TARGET_MHZ]
            if meeting:
                decision = max(meeting, key=lambda r: r[2] / max(r[1]["area_mm2"], 1e-9))
                label, whole, served, _ = decision
                print(f"\n  DECISION: {label}")
                print(f"    {served:.1f} words/cycle at {whole['area_mm2']:.4f} mm2 and "
                      f"{whole['fmax_mhz']:.0f} MHz ({whole['power_total_w']*1e3:.1f} mW) — "
                      f"{served / whole['area_mm2']:.0f} words/cycle per mm2, the best ratio "
                      f"among finalists that clear {TARGET_MHZ:.0f} MHz on placed silicon.")
            else:
                print(f"\n  NO DECISION: none of the finalists clears {TARGET_MHZ:.0f} MHz "
                      "once placed whole. The screen's frequencies do not survive placement, "
                      "which is a result about the screen, not a shortlist.")

    try:
        banks_mm2, note = bank_area_mm2()
        print(f"\nMEMORY SERVED: {BANKS} banks x {BANK_ROWS} rows x {WIDTH_BITS}b = "
              f"{banks_mm2:.4f} mm2")
        if qualifying:
            print(f"  the highest-throughput fabric is "
                  f"{best[1]['area_mm2'] / banks_mm2 * 100:.1f}% of it")
        print(f"  ({note[:100]}...)")
    except Exception as exc:  # noqa: BLE001 — context, not the result
        print(f"\n(memory characterization unavailable: {type(exc).__name__}: {exc})")

    print(f"\nre-query this store yourself with the same tools Flux used:")
    print(f"  nix develop .#physical --command python3 -c \"from flux_chia_nodes import "
          f"flux_campaign_frontier; import json; print(json.dumps("
          f"flux_campaign_frontier('{args.db}', '{results[-1]['campaign_id']}'), indent=2))\"")
    return 0


if __name__ == "__main__":
    sys.exit(main())
