#!/usr/bin/env python3
"""MAC processing-element microarchitecture DSE on real ASAP7 numbers (docs/decisions.md D365).

    nix develop .#physical --command python3 applications/macarray/demo.py
    nix develop .#physical --command python3 applications/macarray/demo.py --target-mhz 1500 --invent 2

The array is given: `--lanes` products summed per cycle at the precision the workload IR
declares. What is searched is inside the PE: the multiplier structure, the reduction, the
pipeline depth. Every design is generated by code, verified by Verilator against golden
vectors, screened by Yosys + OpenSTA, and the finalists along the fmax-vs-area frontier are
placed by OpenROAD. Runs without a model; `--invent N` asks a local model for N multiplier
structures the enumeration does not contain.
"""

from __future__ import annotations

import sys
from pathlib import Path

FLUX_ROOT = Path(__file__).resolve().parents[2]
for sub in ("applications/macarray/lib/src", "interfaces/chia_nodes/src"):
    sys.path.insert(0, str(FLUX_ROOT / sub))


def _print(out: dict) -> None:
    print()
    print("=" * 78)
    d = out.get("decision")
    if d:
        met = out.get("met_requirement")
        print("DECISION -- build this" if met else "DECISION -- the best measured, target NOT met")
        print(f"  PE               {d['label']}")
        print(f"  fmax             {d['fmax_mhz']:.0f} MHz  (worst path {d['path_ps']:.0f} ps, "
              f"{d['flow_depth']})")
        print(f"  area             {d['area_um2']:,.0f} um2   ({d['cell_count']} cells)")
        print(f"  power            {d['power_w'] * 1e3:.2f} mW at {1e6 / d['clock_period_ps']:.0f} MHz")
        print(f"  latency          {d['latency_cycles']} cycle(s)")
        print(f"  chosen by        {out.get('decided_by')}")
        if (out.get("provenance") or {}).get("preserve_fmax"):
            print(f"  clock floor      {(out['provenance'].get('target_mhz') or 0):.0f} MHz, the "
                  "incumbent's own")
        inc = out.get("incumbent")
        if inc and inc["label"] != d["label"]:
            print(f"  vs incumbent     {inc['label']}: {inc['fmax_mhz']:.0f} MHz, "
                  f"{inc['area_um2']:,.0f} um2  ->  {d['fmax_mhz'] / inc['fmax_mhz']:.2f}x clock, "
                  f"{d['area_um2'] / inc['area_um2']:.2f}x area")
        print(f"  shape            {out.get('shape')}")
        print()
        print("-" * 78)
    front = out.get("frontier") or []
    if len(front) > 1:
        rung = front[0]["flow_depth"]
        print(f"FRONTIER  fmax vs area, {rung}; each row is faster than everything smaller")
        print(f"  {'area um2':>10}  {'fmax MHz':>8}  {'this step buys':<26}  {'PE':<26} lat")
        prev = None
        for row in front:
            step = ""
            if prev:
                step = f"{row['fmax_mhz'] - prev['fmax_mhz']:+.0f} MHz for {row['area_um2'] - prev['area_um2']:+.0f} um2"
            mark = "   <- DECISION" if d and row["label"] == d["label"] else ""
            print(f"  {row['area_um2']:>10,.0f}  {row['fmax_mhz']:>8.0f}  {step:<26}  "
                  f"{row['label']:<26} {row['latency_cycles']}{mark}")
            prev = row
        print()
        print("-" * 78)
    from flux_report import established, not_established, refused

    if out.get("lessons"):
        print("\n".join(established(out["lessons"])))
    for block in (not_established(out.get("not_established") or []),
                  refused(out.get("refused") or [],
                          render=lambda i: f"{i['config']}: {i['why']}")):
        if block:
            print("\n" + "\n".join(block))
    prov = out.get("provenance") or {}
    print(f"\nCOST  {prov.get('measurements_run', 0)} measurement(s) run, "
          f"{prov.get('cache_hits', 0)} served from cache, {prov.get('wall_clock_s', 0)}s wall clock")
    print("=" * 78)


def main() -> int:
    import argparse

    sys.stdout.reconfigure(line_buffering=True)
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--db", default="demo-macarray.db",
                    help="where measurements accumulate; a resumed run re-measures nothing")
    ap.add_argument("--workload", default=None,
                    help="a Workload IR document; its einsum's precision sets the PE's "
                         "(default: core/ir/workload/examples/mlp-gemm0.yaml, int8 x int8)")
    ap.add_argument("--lanes", type=int, default=8, help="products summed per cycle (default 8)")
    ap.add_argument("--no-accumulate", action="store_true",
                    help="a dot-product PE with no accumulator input")
    ap.add_argument("--target-mhz", type=float, default=1000.0,
                    help="the clock the PE must make; the decision is the smallest that does "
                         "(default 1000). 0 for no target: the fastest wins")
    ap.add_argument("--preserve-fmax", action="store_true",
                    help="area is the objective: the target becomes the incumbent's own measured "
                         "clock on each rung, and the decision is the smallest PE that holds it")
    ap.add_argument("--mappings", nargs="+", default=None,
                    help="restrict the mapper's recipe: delay (ABC given the period) and/or area")
    ap.add_argument("--clock-period-ps", type=float, default=None,
                    help="what the tools are constrained to (default: the target's period)")
    ap.add_argument("--multipliers", nargs="+", default=None,
                    help="restrict the multiplier structures (behavioral array booth4 wallace)")
    ap.add_argument("--reducers", nargs="+", default=None, help="restrict to chain tree csa")
    ap.add_argument("--pipelines", nargs="+", type=int, default=None, help="restrict to 0 1 2 3")
    ap.add_argument("--invent", type=int, default=0, metavar="N",
                    help="ask the local model for N new multiplier structures; each that passes "
                         "its vectors is kept under applications/macarray/invented and measured")
    ap.add_argument("--no-invented", action="store_true",
                    help="leave kept inventions off the menu")
    ap.add_argument("--decide-on-finalists", type=int, default=4, metavar="N",
                    help="place N designs spread along the screened frontier (default 4)")
    ap.add_argument("--screen-only", action="store_true", help="no placement; screen numbers only")
    ap.add_argument("--workers", type=int, default=0,
                    help="tool processes in flight (default: cores/4, capped at 8)")
    ap.add_argument("--problem", default=None, help="what you need, in words, for the model")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--tui", action="store_true",
                    help="run under the flux TUI (tasks, timing, results, log; D390)")
    args = ap.parse_args()

    from flux_chia_nodes.macarray_dse_loop import flux_macarray_dse_loop

    def _run(fb=None):
        return flux_macarray_dse_loop(
            args.db, workload=args.workload, lanes=args.lanes, accumulate=not args.no_accumulate,
            target_mhz=args.target_mhz or None, preserve_fmax=args.preserve_fmax,
            clock_period_ps=args.clock_period_ps,
            multipliers=args.multipliers, reducers=args.reducers, pipelines=args.pipelines,
            mappings=args.mappings,
            invent_rounds=args.invent, include_invented=not args.no_invented,
            decide_on_finalists=args.decide_on_finalists, screen_only=args.screen_only,
            workers=args.workers, problem=args.problem, seed=args.seed, feedback=fb)

    from flux_tui import demo_run

    try:
        out = demo_run(_run, tui=args.tui, title="flux · macarray", subtitle=args.db,
                       print_report=_print,
                       info={"db": args.db, "lanes": args.lanes,
                             "target MHz": args.target_mhz,
                             "invent rounds": args.invent, "seed": args.seed})
    except KeyboardInterrupt:
        print("run abandoned; partial state is in the db")
        return 130
    _print(out)
    try:
        from flux_report.progress import Point, render_progress

        rows = (out.get("screened") or []) + (out.get("confirmed") or [])
        points = [Point(quality=r["fmax_mhz"], cost=r["area_um2"], label=r["label"],
                        confirmed=(r["flow_depth"] == "placement")) for r in rows]
        if points:
            d = out.get("decision") or {}
            path = render_progress(
                points, out=f"{args.db}.progress.svg", title="MAC-PE DSE progress",
                quality_label="fmax (MHz)", cost_label="area (um2)",
                refused=len(out.get("refused") or []), decision_label=d.get("label"),
                log_cost=False, incumbent_label="behavioral-tree-p0",
                target_quality=(out.get("provenance") or {}).get("target_mhz"),
                target_label="target clock")
            print(f"progress plot: {path}")
    except Exception as exc:                                              # noqa: BLE001
        print(f"(no progress plot: {type(exc).__name__}: {exc})")
    return 0 if out.get("met_requirement") else 1


if __name__ == "__main__":
    sys.exit(main())
