"""Generate the documentation site's tool-catalog pages from the live MCP surface.

The site's "modules" section is not hand-written: `flux_omni.catalog.build_catalog()` replays
`FluxTool.setup()`'s own registrations (the same introspection the omni loop plans over), and
this script renders each `ToolSpec` into grouped Markdown pages under `website/docs/catalog/`.
A hand-maintained catalog page would rot exactly the way D95/D96 measured; this one cannot,
because `flux/tests/unit/test_site_catalog_freshness.py` regenerates it and diffs.

The one thing introspection cannot supply is grouping: `ToolSpec` carries no topic, so `GROUPS`
below assigns every tool to a page by name, and `generate()` refuses to run when the mapping and
the live catalog disagree in either direction -- a newly registered tool forces a conscious
grouping choice here, the same discipline as `test_mcp_surface_parity.py`.

The rendering is the site's own, not `ToolSpec.render()` (D389): that flat bullet form is the
shape a MODEL copies arguments out of, and on a page it reads as a wall of text. A reader gets
each tool as a heading (so the page's table of contents lists them), its summary, the required
parameters in a small table, and the optional ones -- which dominate, several tools take 15+ --
folded into a collapsible table with their defaults. Same introspected content, reader-shaped.

Run it from the dev shell (importing flux_mcp needs the flake's PYTHONPATH):

    cd flux && nix develop --command python3 ../website/generate_catalog.py
"""

from __future__ import annotations

import sys
from pathlib import Path

_CATALOG_DIR = Path(__file__).resolve().parent / "docs" / "catalog"

_HEADER = (
    "<!-- GENERATED by website/generate_catalog.py -- do not edit by hand.\n"
    "     Regenerate: cd flux && nix develop --command python3 ../website/generate_catalog.py -->\n"
)

# page slug -> (page title, one-paragraph intro)
PAGES: dict[str, tuple[str, str]] = {
    "loops": (
        "Design loops",
        "Complete searches, one call each: the per-application loops the demos run, plus the "
        "reference agentic loop and the code-space rung that invents new prefetchers. Every "
        "loop runs without a model; a local model fills a named role when one is available.",
    ),
    "search": (
        "Search and sweeps",
        "Single-axis and joint searches over one design space, and sweeps that resolve dynamic "
        "workload shapes. These are the pieces the loops above are built from.",
    ),
    "campaign": (
        "Campaigns and records",
        "Long-running searches as a stepped campaign, plus read-only access to everything "
        "already measured: results by lineage, leaderboards, and the public benchmark corpus.",
    ),
    "evaluate": (
        "Evaluation and calibration",
        "Score one candidate through a real tool backend, widen its confidence interval from "
        "calibration residuals, check validity and conformance, and explain what the numbers "
        "mean.",
    ),
    "generate": (
        "Generation and synthesis",
        "Make designs and code from instructions -- architecture candidates, RTL and SystemC "
        "modules, composed designs -- and put them through real synthesis on ASAP7.",
    ),
    "knowledge": (
        "Knowledge and protocols",
        "The corpus and the facts mined from it, protocol structure (signals, parameters, "
        "rules) with provenance, and checks that prose and IR stay faithful to both.",
    ),
}

# tool bare name -> page slug. Explicit on purpose: generate() fails on any tool the live
# catalog has that this table lacks, and on any row here the catalog no longer registers.
GROUPS: dict[str, str] = {
    # loops
    "agentic_dse_loop": "loops",
    "agentic_multi_axis_dse": "loops",
    "bankmap_dse_loop": "loops",
    "nlu_dse_loop": "loops",
    "interconnect_dse_loop": "loops",
    "interconnect_mapping_dse_loop": "loops",
    "invent_prefetcher": "loops",
    "macarray_dse_loop": "loops",
    "prefetcher_dse_loop": "loops",
    # search
    "agentic_architecture_search": "search",
    "agentic_joint_search": "search",
    "agentic_mapping_search": "search",
    "agentic_memory_search": "search",
    "agentic_noc_search": "search",
    "rtl_generate_dse": "search",
    "search": "search",
    "sweep_dynamic_shape": "search",
    "sweep_moe_routing": "search",
    "systemc_generate_dse": "search",
    # campaign
    "campaign_frontier": "campaign",
    "campaign_resume": "campaign",
    "campaign_start": "campaign",
    "campaign_status": "campaign",
    "campaign_step": "campaign",
    "campaign_stop": "campaign",
    "find_results": "campaign",
    "get_result": "campaign",
    "leaderboard": "campaign",
    "list_public_corpus": "campaign",
    # evaluate
    "backend_health": "evaluate",
    "calibrate": "evaluate",
    "calibrate_against_generated_rtl": "evaluate",
    "champsim_run": "evaluate",
    "characterize_memory_level": "evaluate",
    "check_validity": "evaluate",
    "conformance_check": "evaluate",
    "evaluate": "evaluate",
    "explain_candidate": "evaluate",
    # generate
    "author_design_spec": "generate",
    "author_objective": "generate",
    "compose_and_verify_rtl_design": "generate",
    "compose_and_verify_systemc_design": "generate",
    "generate_architecture_candidate": "generate",
    "generate_gemm_rtl_for_architecture": "generate",
    "generate_rtl_for_architecture": "generate",
    "generate_rtl_module": "generate",
    "generate_sequential_rtl_for_architecture": "generate",
    "generate_systemc_module": "generate",
    "synthesize_composite_rtl_design": "generate",
    "synthesize_with_asap7": "generate",
    "synthesize_with_asap7_redacted": "generate",
    # knowledge
    "check_ir_protocols": "knowledge",
    "check_prose_faithfulness": "knowledge",
    "check_protocol_conformance": "knowledge",
    "ip_catalog": "knowledge",
    "knowledge_lookup": "knowledge",
    "list_protocols": "knowledge",
    "mine_knowledge": "knowledge",
    "protocol_lookup": "knowledge",
    "recall_facts": "knowledge",
}


def _cell(text: str) -> str:
    """One markdown table cell: pipes escaped, newlines flattened, and the first-sentence
    truncation's dangling ', e.g.' fragment dropped (the catalog cuts arg docs at the first
    sentence; on a page the stub invites an example that never comes)."""
    import re

    text = " ".join(str(text).split()).replace("|", "\\|")
    return re.sub(r"[,;]?\s*\(?\s*e\.g\.$", "", text).strip()


def _param_rows(params, *, with_default: bool) -> list[str]:
    head = ("| parameter | type | default | what it is |", "|---|---|---|---|") \
        if with_default else ("| parameter | type | what it is |", "|---|---|---|")
    rows = list(head)
    for p in params:
        default = f" `{_cell(repr(p.default))}` |" if with_default else ""
        rows.append(f"| `{p.name}` | `{_cell(p.annotation)}` |{default} {_cell(p.doc)} |")
    return rows


def _render_tool(spec) -> str:
    """One tool, shaped for a reader: heading, summary, required up front, optionals folded."""
    lines = [f"## {spec.name}", "", spec.summary]
    required = [p for p in spec.params if p.required]
    optional = [p for p in spec.params if not p.required]
    if required:
        lines += ["", *_param_rows(required, with_default=False)]
    if optional:
        n = len(optional)
        lines += ["", f'??? note "{n} optional parameter{"s" if n > 1 else ""}"', ""]
        lines += [f"    {row}" for row in _param_rows(optional, with_default=True)]
    return "\n".join(lines)


# Per-page worked examples: the three call surfaces on ONE concrete invocation, so a
# reader leaves each page knowing how to hold the tools. Curated here (introspection
# cannot invent inputs), kept inside the generator so the freshness test still
# guards the whole page byte for byte.
EXAMPLES: dict[str, str] = {
    "evaluate": """## Worked example

The same evaluation on all three surfaces -- library call, CHIA node, CLI:

=== "Python"

    ```python
    from flux_cli.registry import make_evaluator
    from flux_evaluator_abi import Budget, Candidate
    import flux_ir

    workload = flux_ir.load_document("core/ir/workload/examples/mlp-gemm0.yaml")
    arch = flux_ir.load_document("core/ir/architecture/examples/simple-npu-1d-v1.yaml")
    result = make_evaluator("zigzag").evaluate(
        Candidate(workload=workload, arch=arch, mapping=None),
        Budget(), frozenset({"latency_cycles", "energy_pj"}))
    print(result.metrics["latency_cycles"].value)   # 1554.0, analytic, with CI
    ```

=== "CHIA node / MCP"

    ```python
    from flux_chia_nodes import flux_evaluate

    report = flux_evaluate("zigzag", workload, arch)      # same call, JSON-safe dict
    ```

    Over MCP the tool is `flux_evaluate` with the same parameters; the
    [omni loop](../demos/omni.md) plans over exactly this surface.

=== "CLI"

    ```bash
    nix develop --command flux eval --backend zigzag \\
        --workload core/ir/workload/examples/mlp-gemm0.yaml \\
        --arch core/ir/architecture/examples/simple-npu-1d-v1.yaml
    ```

Swap `zigzag` for any backend in the table above; `backend_health` reports which are
usable on this machine and why the others are not.
""",
    "knowledge": """## Worked example

    ```python
    from flux_chia_nodes import flux_knowledge_lookup

    hits = flux_knowledge_lookup("bank conflict avoidance for strided access")
    for h in hits["results"][:3]:
        print(h["source"], "->", h["text"][:80])
    ```

Every chunk carries its source and license; the corpus is curated from
permissively-licensed material, never scraped (see the guidance the
[loop shape](../guide/loop-shape.md) page gives the mentor role).
""",
    "loops": """## Worked example

    ```python
    from flux_chia_nodes import flux_interconnect_mapping_dse_loop

    out = flux_interconnect_mapping_dse_loop(seed=0, climb_rounds=40)
    print(out["conclusion"]["balanced_pick"])   # the knee of the 4-cost front
    ```

Each loop is also a demo (`applications/<name>/demo.py`) with `--tui`, and each
returns the same decision-first record its demo prints.
""",
}


def _backend_rows() -> list[str]:
    """The evaluator-backend table, generated from the live registry: every name in
    `available_backends()` with the first line of its adapter module's docstring.
    Import only -- no instantiation, no tool probing -- so the output is identical on
    every machine and the freshness guard stays meaningful."""
    import importlib

    from flux_cli.registry import available_backends

    rows = ["## Evaluator backends", "",
            "Sixteen adapters behind one ABI; pass any of these as `backend`:", "",
            "| backend | what it is |", "|---|---|"]
    for name in available_backends():
        try:
            mod = importlib.import_module(f"flux_evaluator_{name}")
            doc = (mod.__doc__ or "").strip().split("\n")[0].rstrip(".")
        except Exception as exc:  # noqa: BLE001 -- a missing adapter is a row, not a crash
            doc = f"(module unavailable: {type(exc).__name__})"
        rows.append(f"| `{name}` | {doc} |")
    return rows


def generate() -> dict[Path, str]:
    """Render every catalog page, `{absolute path: content}`, writing nothing."""
    from flux_omni.catalog import build_catalog

    catalog = build_catalog()

    unmapped = sorted(catalog.keys() - GROUPS.keys())
    dead = sorted(GROUPS.keys() - catalog.keys())
    if unmapped or dead:
        raise SystemExit(
            "GROUPS in website/generate_catalog.py disagrees with the live catalog -- "
            f"unmapped tools: {unmapped or 'none'}; mapped but no longer registered: "
            f"{dead or 'none'}. Assign or remove them, then regenerate."
        )

    pages: dict[Path, str] = {}
    for slug, (title, intro) in PAGES.items():
        specs = [catalog[n] for n in sorted(catalog) if GROUPS[n] == slug]
        body = "\n\n".join(_render_tool(spec) for spec in specs)
        extras = ""
        if slug == "evaluate":
            extras += "\n".join(_backend_rows()) + "\n\n"
        if slug in EXAMPLES:
            extras += EXAMPLES[slug] + "\n"
        content = f"{_HEADER}# {title}\n\n{intro}\n\n{extras}{body}\n"
        pages[_CATALOG_DIR / f"{slug}.md"] = content
    return pages


def main() -> None:
    _CATALOG_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in generate().items():
        path.write_text(content)
        print(f"wrote {path}", file=sys.stderr)


if __name__ == "__main__":
    main()
